version: '3'
services:
  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    command: sh -c 'yarn dev'
  admin:
    container_name: admin
    build: ./admin
    volumes:
      - ./admin:/admin
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    command: sh -c 'yarn dev'
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: dockerMySQL
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  mysql:
    container_name: dockerMySQL
    image: mysql:5.7.10
    ports:
      - 3306:3306
    volumes:
      - ./db-init/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-init/scheme:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'