version: '3'
services:
  app:
    build: ./frontend
    container_name: app
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: sh -c 'yarn dev'
    ports:
      - 3000:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}