version: '3'
services:
  app:
  mysql:
    image: "mysql:5.7.10"
    charset: utf8
    encoding: utf8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

